[package]
name = "sucocku"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.0"
directories = "6.0.0"
macroquad = "0.4.14"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
