# Colors that define various UI elements.
# The values represent [r, g, b, a]. 0 is minimum value, 1 is maximum value
[colors]
outer_line  = [0.0, 0.0, 0.0, 1]
box_line    = [0.0, 0.0, 0.0, 1]
normal_line = [0.5, 0.5, 0.5, 1]

normal_font_color = [1.0, 1.0, 1.0, 1]
note_font_color   = [0.9, 0.9, 0.9, 1]

# Thickness of various lines
[lines]
outer_line_width  = 5
box_line_width    = 3
normal_line_width = 1
